"use-client";
import Providers from '@/lib/Providers';
import './globals.css';
import Navbar from '@/components/Navbar';


export const metadata = {
  title: 'Social Services Club',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <Providers>
      <html lang="en">
        <body>
          <Navbar/>
          <main>{children}</main> {/* Add top padding to avoid overlap with fixed navbar */}
        </body>
      </html>
    </Providers>
  );
}
