import Providers from '@/lib/Providers';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Social Services Club',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>
          <main className="pt-16 mt-16">{children}</main> {/* Add padding to avoid overlap */}
        </body>
      </html>
    </Providers>
  );
}
