import Providers from '@/lib/Providers';
import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Social Services Club',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>
          <Navbar/>
          <main>{children}</main> {/* Add top padding to avoid overlap with fixed navbar */}
        </body>
      </html>
    </Providers>
  );
}
